# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: mysql2
  database: data_population_development
  username: root
  password: Mysql@2024
  host: localhost
  port: 3306
test:
  adapter: mysql2
  database: data_population_test
  username: root
  password: Mysql@2024
  host: localhost
  port: 3306
production:
  adapter: mysql2
  database: data_population_production
  username: root
  password: Mysql@2024
  host: localhost
  port: 3306